version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - 9092:9092
    hostname: kafka
    extra_hosts:
      - "kafka:127.0.0.1 "
    environment:
      KAFKA_CREATE_TOPICS: "axon-events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  mysql-axon:
    image: mysql:5.7
    container_name: mysql-axon
    networks:
      - kafkanet
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3314:3306
    volumes:
      - ./volume/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./volume/mysql/conf.d:/etc/mysql/conf.d
      - ./volume/mysql/log:/var/log/mysql
      - ./volume/mysql/db:/var/lib/mysql
      - ./volume/my.cnf:/etc/my.cnf

networks:
  kafkanet:
    driver: bridge